export const APP_ICON_SET = "tabler" as const

export const APP_ICONS = {
  dashboard: "tabler:layout-dashboard",
  salons: "tabler:flower",
  spa: "tabler:flower",
  branches: "tabler:git-branch",
  users: "tabler:users",
  user: "tabler:user",
  userPlus: "tabler:user-plus",
  userCircle: "tabler:user-circle",
  userCheck: "tabler:user-check",
  userOff: "tabler:user-off",
  userGroup: "tabler:users-group",
  clients: "tabler:heart-handshake",
  clientFolder: "tabler:folder-heart",
  appointments: "tabler:calendar-time",
  calendar: "tabler:calendar",
  calendarMonth: "tabler:calendar-month",
  calendarToday: "tabler:calendar-event",
  calendarCheck: "tabler:calendar-check",
  calendarClock: "tabler:calendar-time",
  sales: "tabler:cash-register",
  cashPlus: "tabler:cash-banknote",
  cashMultiple: "tabler:cash",
  reports: "tabler:chart-bar",
  commissions: "tabler:coins",
  serviceCategories: "tabler:tags",
  services: "tabler:scissors",
  menu: "tabler:menu-2",
  menuCollapse: "tabler:layout-sidebar-left-collapse",
  menuExpand: "tabler:layout-sidebar-left-expand",
  close: "tabler:x",
  cancel: "tabler:ban",
  chevronDown: "tabler:chevron-down",
  chevronUp: "tabler:chevron-up",
  chevronLeft: "tabler:chevron-left",
  chevronRight: "tabler:chevron-right",
  arrowLeft: "tabler:arrow-left",
  logout: "tabler:logout",
  plus: "tabler:plus",
  search: "tabler:search",
  download: "tabler:download",
  help: "tabler:help-circle",
  edit: "tabler:pencil",
  delete: "tabler:trash",
  view: "tabler:eye",
  eyeOff: "tabler:eye-off",
  store: "tabler:building-store",
  domain: "tabler:building",
  city: "tabler:building-community",
  mapPin: "tabler:map-pin",
  phone: "tabler:phone",
  email: "tabler:mail",
  lock: "tabler:lock",
  lockCheck: "tabler:lock-check",
  lockReset: "tabler:lock-password",
  receipt: "tabler:receipt-2",
  checkCircle: "tabler:circle-check",
  checks: "tabler:checks",
  closeCircle: "tabler:circle-x",
  circle: "tabler:circle",
  clock: "tabler:clock",
  clockAlert: "tabler:clock-exclamation",
  playCircle: "tabler:player-play",
  table: "tabler:table",
  tableSearch: "tabler:search",
  list: "tabler:list",
  package: "tabler:package",
  shieldUser: "tabler:shield-cog",
  roleChange: "tabler:shield-cog",
  clipboardText: "tabler:clipboard-text",
  clipboardPulse: "tabler:activity-heartbeat",
  clipboardPulseOutline: "tabler:clipboard-heart",
  fileDocument: "tabler:file-text",
  fileSearch: "tabler:file-search",
  stethoscope: "tabler:stethoscope",
  medicalBag: "tabler:medical-cross",
  notes: "tabler:notes",
  history: "tabler:history",
  trashCan: "tabler:trash",
  cake: "tabler:cake",
  gender: "tabler:gender-bigender",
  currency: "tabler:currency-dollar",
  settings: "tabler:settings",
  imageUpload: "tabler:photo-plus",
  success: "tabler:circle-check",
  error: "tabler:alert-circle",
  info: "tabler:info-circle",
  warning: "tabler:alert-triangle",
} as const

export type AppIconName = (typeof APP_ICONS)[keyof typeof APP_ICONS]

export const MDI_TO_TABLER: Record<string, string> = {
  "mdi-account-plus-outline": APP_ICONS.userPlus,
  "mdi-close": APP_ICONS.close,
  "mdi-store-outline": APP_ICONS.store,
  "mdi-map-marker-outline": APP_ICONS.mapPin,
  "mdi-city-variant-outline": APP_ICONS.city,
  "mdi-pencil": APP_ICONS.edit,
  "mdi-pencil-outline": APP_ICONS.edit,
  "mdi-delete": APP_ICONS.delete,
  "mdi-delete-outline": APP_ICONS.delete,
  "mdi-domain": APP_ICONS.domain,
  "mdi-plus": APP_ICONS.plus,
  "mdi-chevron-left": APP_ICONS.chevronLeft,
  "mdi-chevron-right": APP_ICONS.chevronRight,
  "mdi-chevron-up": APP_ICONS.chevronUp,
  "mdi-chevron-down": APP_ICONS.chevronDown,
  "mdi-calendar-check": APP_ICONS.calendarCheck,
  "mdi-cash-register": APP_ICONS.sales,
  "mdi-hand-coin-outline": APP_ICONS.commissions,
  "mdi-receipt-text-outline": APP_ICONS.receipt,
  "mdi-cash-multiple": APP_ICONS.cashMultiple,
  "mdi-check-circle-outline": APP_ICONS.checkCircle,
  "mdi-clock-outline": APP_ICONS.clock,
  "mdi-download": APP_ICONS.download,
  "mdi-magnify": APP_ICONS.search,
  "mdi-table-search": APP_ICONS.tableSearch,
  "mdi-help-circle-outline": APP_ICONS.help,
  "mdi-cash-plus": APP_ICONS.cashPlus,
  "mdi-eye-outline": APP_ICONS.view,
  "mdi-eye-off-outline": APP_ICONS.eyeOff,
  "mdi-cancel": APP_ICONS.cancel,
  "mdi-package-variant-closed": APP_ICONS.package,
  "mdi-email-outline": APP_ICONS.email,
  "mdi-lock-outline": APP_ICONS.lock,
  "mdi-lock-check-outline": APP_ICONS.lockCheck,
  "mdi-lock-reset": APP_ICONS.lockReset,
  "mdi-calendar": APP_ICONS.calendar,
  "mdi-calendar-outline": APP_ICONS.calendar,
  "mdi-calendar-month-outline": APP_ICONS.calendarMonth,
  "mdi-account-outline": APP_ICONS.user,
  "mdi-account-group-outline": APP_ICONS.userGroup,
  "mdi-calendar-today": APP_ICONS.calendarToday,
  "mdi-play-circle-outline": APP_ICONS.playCircle,
  "mdi-check-all": APP_ICONS.checks,
  "mdi-scissors-cutting": APP_ICONS.services,
  "mdi-source-branch": APP_ICONS.branches,
  "mdi-folder-heart-outline": APP_ICONS.clientFolder,
  "mdi-circle-outline": APP_ICONS.circle,
  "mdi-spa-outline": APP_ICONS.spa,
  "mdi-calendar-clock": APP_ICONS.calendarClock,
  "mdi-calendar-clock-outline": APP_ICONS.calendarClock,
  "mdi-account-circle-outline": APP_ICONS.userCircle,
  "mdi-cake-variant-outline": APP_ICONS.cake,
  "mdi-human-male-female": APP_ICONS.gender,
  "mdi-close-circle-outline": APP_ICONS.closeCircle,
  "mdi-account-off-outline": APP_ICONS.userOff,
  "mdi-table": APP_ICONS.table,
  "mdi-shield-account-outline": APP_ICONS.shieldUser,
  "mdi-account-check-outline": APP_ICONS.userCheck,
  "mdi-clipboard-pulse-outline": APP_ICONS.clipboardPulseOutline,
  "mdi-clipboard-pulse": APP_ICONS.clipboardPulse,
  "mdi-file-document-outline": APP_ICONS.fileDocument,
  "mdi-stethoscope": APP_ICONS.stethoscope,
  "mdi-medical-bag": APP_ICONS.medicalBag,
  "mdi-note-text-outline": APP_ICONS.notes,
  "mdi-clock-alert-outline": APP_ICONS.clockAlert,
  "mdi-history": APP_ICONS.history,
  "mdi-trash-can-outline": APP_ICONS.trashCan,
  "mdi-arrow-left": APP_ICONS.arrowLeft,
  "mdi-clipboard-text-outline": APP_ICONS.clipboardText,
  "mdi-format-list-bulleted": APP_ICONS.list,
  "mdi-currency-usd": APP_ICONS.currency,
  "mdi-alert-circle-outline": APP_ICONS.error,
  "mdi-information-outline": APP_ICONS.info,
  "mdi-alert-outline": APP_ICONS.warning,
  "mdi-file-search-outline": APP_ICONS.fileSearch,
  "mdi-phone-outline": APP_ICONS.phone,
  "mdi-backburger": APP_ICONS.menu,
  "mdi-menu": APP_ICONS.menu,
  "mdi-view-dashboard-outline": APP_ICONS.dashboard,
  "mdi-account-cog-outline": APP_ICONS.users,
  "mdi-account-heart-outline": APP_ICONS.clients,
  "mdi-tag-multiple-outline": APP_ICONS.serviceCategories,
  "mdi-chart-bar": APP_ICONS.reports,
  "mdi-chevron-double-right": APP_ICONS.menuExpand,
  "mdi-chevron-double-left": APP_ICONS.menuCollapse,
  "mdi-menu-down": APP_ICONS.chevronDown,
  "mdi-menu-right": APP_ICONS.chevronRight,
  "mdi-page-first": "tabler:chevrons-left",
  "mdi-page-last": "tabler:chevrons-right",
  "mdi-check": "tabler:check",
  "mdi-checkbox-marked": "tabler:square-check-filled",
  "mdi-checkbox-blank-outline": "tabler:square",
  "mdi-minus-box": "tabler:square-minus-filled",
  "mdi-arrow-up": "tabler:arrow-up",
  "mdi-arrow-down": "tabler:arrow-down",
  "mdi-arrow-right": "tabler:arrow-right",
  "mdi-radiobox-marked": "tabler:circle-dot-filled",
  "mdi-radiobox-blank": APP_ICONS.circle,
  "mdi-star-outline": "tabler:star",
  "mdi-star": "tabler:star-filled",
  "mdi-star-half-full": "tabler:star-half-filled",
  "mdi-cached": "tabler:loader-2",
  "mdi-unfold-more-horizontal": "tabler:chevrons-down",
  "mdi-paperclip": "tabler:paperclip",
  "mdi-minus": "tabler:minus",
  "mdi-eyedropper": "tabler:color-picker",
  "mdi-cloud-upload": "tabler:cloud-upload",
  "mdi-palette": "tabler:palette",
  "mdi-play": "tabler:player-play",
  "mdi-pause": "tabler:player-pause",
  "mdi-fullscreen": "tabler:maximize",
  "mdi-fullscreen-exit": "tabler:minimize",
  "mdi-volume-high": "tabler:volume",
  "mdi-volume-medium": "tabler:volume-2",
  "mdi-volume-low": "tabler:volume-3",
  "mdi-volume-variant-off": "tabler:volume-off",
  "mdi-backspace": "tabler:backspace",
  "mdi-check-circle": APP_ICONS.checkCircle,
  "mdi-information": APP_ICONS.info,
  "mdi-alert-circle": APP_ICONS.error,
  "mdi-close-circle": APP_ICONS.closeCircle,
}

export const isIconifyIcon = (value?: string | null) =>
  Boolean(value && value.includes(":"))

export const resolveAppIcon = (icon?: string | null): string => {
  if (!icon) return APP_ICONS.help

  if (isIconifyIcon(icon)) return icon

  if (icon.startsWith("mdi-")) {
    return MDI_TO_TABLER[icon] ?? APP_ICONS.help
  }

  return icon
}
